---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: three-t-local-data
spec:
  capacity:
    storage: 100Gi
  local:
    path: /srv/three-t-pipeline
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [example-worker]
